eureka:
  client:
    enabled: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth-server.url}/realms/${auth-server.realm}

auth-server:
  url: # set via EnvFile
  realm: # set via EnvFile

one-c:
  host: # set via EnvFile
  username: # set via EnvFile
  password: # set via EnvFile

jira1:
  host: # set via EnvFile
  username: # set via EnvFile
  password: # set via EnvFile

jira2:
  host: # set via EnvFile
  username: # set via EnvFile
  password: # set via EnvFile

employee-service:
  work-day-hours: 8
  user-availability:
    jql: Employee in ({usernames}) AND project in ("Calendar RCIS", "Calendar") AND "Leave from date" <= startOfDay() AND "Leave to date" >= endOfDay() AND status not in (Canceled, Rejected)

logging.level:
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE
