version: '3'

services:
  employee-service:
    container_name: ft-employee-service
    image: ${OCTOPUS_GITHUB_DOCKER_REGISTRY}/octopusden/employee-service:${EMPLOYEE_SERVICE_VERSION}
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_CONFIG_ENABLED=false
      - AUTH_SERVER_URL=${AUTH_SERVER_URL}
      - AUTH_SERVER_REALM=${AUTH_SERVER_REALM}
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/
      - TEST_API_GATEWAY_HOST=${TEST_API_GATEWAY_HOST}
      - TEST_MOCK_SERVER_HOST=${TEST_MOCK_SERVER_HOST}
    volumes:
      - ./employee-service.yaml:/application.yaml

  api-gateway:
    container_name: ft-api-gateway
    image: ${OCTOPUS_GITHUB_DOCKER_REGISTRY}/octopusden/api-gateway:${API_GATEWAY_VERSION}
    ports:
      - "8765:8765"
    volumes:
      - ./api-gateway.yaml:/application.yaml
    environment:
      - SPRING_CLOUD_CONFIG_ENABLED=false
      - AUTH_SERVER_URL=${AUTH_SERVER_URL}
      - AUTH_SERVER_REALM=${AUTH_SERVER_REALM}
      - AUTH_SERVER_CLIENT_ID=${AUTH_SERVER_CLIENT_ID}
      - AUTH_SERVER_CLIENT_SECRET=${AUTH_SERVER_CLIENT_SECRET}
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/
      - TEST_EMPLOYEE_SERVICE_HOST=${TEST_EMPLOYEE_SERVICE_HOST}
      - TEST_API_GATEWAY_HOST_EXTERNAL=${TEST_API_GATEWAY_HOST_EXTERNAL}
    depends_on:
      - employee-service
    healthcheck:
      #unable to use health endpoint: migrateMockData is not done yet -> one-c ping fails
      test: [ "CMD", "curl", "-f", "http://localhost:8765/employee-service/actuator/info" ]
      interval: 10s
      timeout: 30s
      retries: 50

  mockserver:
    container_name: ft-mockserver
    image: ${DOCKER_REGISTRY}/mockserver/mockserver:mockserver-${MOCK_SERVER_VERSION}
    ports:
      - "1080:1080"