eureka:
  client:
    enabled: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth-server.url}/realms/${auth-server.realm}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
    loggers:
      enabled: true

auth-server:
  url: # set via env
  logout-url: ${auth-server.url}/realms/${auth-server.realm}/protocol/openid-connect/logout?redirect_uri=http://localhost:8765/employee-service/swagger-ui/index.html
  realm: # set via env

employee-service:
  work-day-hours: 8
  user-availability:
    jql: Employee in ({usernames}) AND project in ("Calendar RCIS", "Calendar") AND "Leave from date" <= startOfDay() AND "Leave to date" >= endOfDay() AND status not in (Canceled, Rejected)

one-c:
  host: http://mockserver:1080/one-c
  username: oneCUser
  password: oneCPassword

jira1:
  host: http://mockserver:1080/jira1
  username: jiraUser
  password: jiraPassword

jira2:
  host: http://mockserver:1080/jira2
  username: jira2User
  password: jira2Password

logging.level:
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE

server:
  forward-headers-strategy: framework

octopus-security:
  roles:
    ROLE_EMPLOYEE_SERVICE_USER_DEV:
      - ACCESS_EMPLOYEE
      - ACCESS_CUSTOMER