name: Gradle Compile & UT

on: [push, pull_request, workflow_dispatch]

jobs:
  run-build-and-deploy:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-build.yml@fix-docker-registry-params
    with:
      flow-type: hybrid
      java-version: '11'
      docker-image: employee-service
