name: RELEASE

on:
  repository_dispatch:
    types: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
    - uses: actions/checkout@v3
      name: Checkout(switching to commit)
      with:
        ref: ${{ github.event.client_payload.commit }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'gradle'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: GitHub Tag Name
      run: |
        echo "Current version: ${{ github.event.client_payload.project_version }}"
    - name: Build with Gradle
      run: ./gradlew build dockerBuildImage -x test -Poctopus.github.docker.registry=ghcr.io -Pdocker.registry=docker.io -Pversion=${{ github.event.client_payload.project_version }} --info
      env:
        BUILD_VERSION: ${{ github.event.client_payload.project_version }}
    - name: Publish
      run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -Pversion=${{ github.event.client_payload.project_version }}
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
        BUILD_VERSION: ${{ github.event.client_payload.project_version }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to docker registry
      run: docker push ghcr.io/octopusden/employee-service:${{ github.event.client_payload.project_version }}
    - name: Create Release
      uses: marvinpinto/action-automatic-releases@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        automatic_release_tag: v${{ github.event.client_payload.project_version }}
