name: Sonar

on:
  push:
    branches: [ '**' ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sonar:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-sonar.yml@add-sonarcloud-workflows
    with:
      java-version: '21'
      quality-gate-wait: true
    secrets: inherit
